// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw2_ef.Models;

#nullable disable

namespace cw2_ef.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20260922070419_FirstMig")]
    partial class FirstMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("cw2_ef.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.R.R. Tolkien",
                            Price = 0m,
                            Title = "Władca Pierścieni",
                            Year = 0
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.R.R. Tolkien",
                            Price = 0m,
                            Title = "Hobbit",
                            Year = 0
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            Price = 0m,
                            Title = "1984",
                            Year = 0
                        },
                        new
                        {
                            Id = 4,
                            Author = "Fiodor Dostojewski",
                            Price = 0m,
                            Title = "Zbrodnia i kara",
                            Year = 0
                        },
                        new
                        {
                            Id = 5,
                            Author = "Bolesław Prus",
                            Price = 0m,
                            Title = "Lalka",
                            Year = 0
                        },
                        new
                        {
                            Id = 6,
                            Author = "Adam Mickiewicz",
                            Price = 0m,
                            Title = "Pan Tadeusz",
                            Year = 0
                        },
                        new
                        {
                            Id = 7,
                            Author = "Michaił Bułhakow",
                            Price = 0m,
                            Title = "Mistrz i Małgorzata",
                            Year = 0
                        },
                        new
                        {
                            Id = 8,
                            Author = "Antoine de Saint-Exupéry",
                            Price = 0m,
                            Title = "Mały Książę",
                            Year = 0
                        },
                        new
                        {
                            Id = 9,
                            Author = "J.K. Rowling",
                            Price = 0m,
                            Title = "Harry Potter i Kamień Filozoficzny",
                            Year = 0
                        },
                        new
                        {
                            Id = 10,
                            Author = "Andrzej Sapkowski",
                            Price = 0m,
                            Title = "Wiedźmin: Ostatnie życzenie",
                            Year = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
